// <auto-generated />
using System;
using CupcakeStore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CupcakeStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251109184237_CreateInicial")]
    partial class CreateInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("CupcakeStore.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("Nota")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("CupcakeStore.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("CupcakeStore.Models.Cupcake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Destaque")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estoque")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cupcakes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = 1,
                            Descricao = "Cobertura de brigadeiro e massa de chocolate",
                            Destaque = true,
                            Estoque = 10,
                            ImagemUrl = "/img/chocolate.jpg",
                            Nome = "Cupcake de Chocolate",
                            Preco = 8.50m
                        },
                        new
                        {
                            Id = 2,
                            Categoria = 2,
                            Descricao = "Recheado com geleia de morango e cobertura de chantilly",
                            Destaque = true,
                            Estoque = 10,
                            ImagemUrl = "/img/morango.jpg",
                            Nome = "Cupcake de Morango",
                            Preco = 9.00m
                        },
                        new
                        {
                            Id = 3,
                            Categoria = 3,
                            Descricao = "Sem ingredientes de origem animal",
                            Destaque = false,
                            Estoque = 10,
                            ImagemUrl = "/img/limao.jpg",
                            Nome = "Cupcake Vegano de Limão",
                            Preco = 10.00m
                        },
                        new
                        {
                            Id = 4,
                            Categoria = 4,
                            Descricao = "Clássico red velvet com cobertura de cream cheese",
                            Destaque = true,
                            Estoque = 10,
                            ImagemUrl = "/img/redvelvet.jpg",
                            Nome = "Cupcake de Red Velvet",
                            Preco = 11.50m
                        },
                        new
                        {
                            Id = 5,
                            Categoria = 1,
                            Descricao = "Massa de cenoura e cobertura de chocolate cremoso",
                            Destaque = true,
                            Estoque = 10,
                            ImagemUrl = "/img/cenoura.jpg",
                            Nome = "Cupcake de Cenoura com Chocolate",
                            Preco = 8.00m
                        },
                        new
                        {
                            Id = 6,
                            Categoria = 2,
                            Descricao = "Recheado com doce de leite e cobertura de coco ralado",
                            Destaque = false,
                            Estoque = 10,
                            ImagemUrl = "/img/coco.jpg",
                            Nome = "Cupcake de Coco com Doce de Leite",
                            Preco = 9.50m
                        },
                        new
                        {
                            Id = 7,
                            Categoria = 4,
                            Descricao = "Cobertura de frutas vermelhas e massa de baunilha",
                            Destaque = false,
                            Estoque = 10,
                            ImagemUrl = "/img/frutasvermelhas.jpg",
                            Nome = "Cupcake de Baunilha com Frutas Vermelhas",
                            Preco = 9.20m
                        },
                        new
                        {
                            Id = 8,
                            Categoria = 1,
                            Descricao = "Cobertura de pasta de amendoim cremosa",
                            Destaque = false,
                            Estoque = 10,
                            ImagemUrl = "/img/amendoim.jpg",
                            Nome = "Cupcake de Amendoim",
                            Preco = 8.80m
                        },
                        new
                        {
                            Id = 9,
                            Categoria = 4,
                            Descricao = "Recheado e coberto com Nutella",
                            Destaque = true,
                            Estoque = 10,
                            ImagemUrl = "/img/nutella.jpg",
                            Nome = "Cupcake de Nutella",
                            Preco = 11.00m
                        },
                        new
                        {
                            Id = 10,
                            Categoria = 1,
                            Descricao = "Cobertura de mousse de maracujá e calda azedinha",
                            Destaque = false,
                            Estoque = 10,
                            ImagemUrl = "/img/maracuja.jpg",
                            Nome = "Cupcake de Maracujá",
                            Preco = 9.50m
                        },
                        new
                        {
                            Id = 11,
                            Categoria = 4,
                            Descricao = "Cobertura cremosa com pedaços de biscoito Oreo",
                            Destaque = true,
                            Estoque = 10,
                            ImagemUrl = "/img/oreo.jpg",
                            Nome = "Cupcake de Oreo",
                            Preco = 10.50m
                        },
                        new
                        {
                            Id = 12,
                            Categoria = 4,
                            Descricao = "Recheado com Nutella e cobertura de Leite Ninho",
                            Destaque = true,
                            Estoque = 10,
                            ImagemUrl = "/img/leiteninho.jpg",
                            Nome = "Cupcake de Leite Ninho com Nutella",
                            Preco = 11.90m
                        },
                        new
                        {
                            Id = 13,
                            Categoria = 1,
                            Descricao = "Massa de café com cobertura de chantilly de cappuccino",
                            Destaque = false,
                            Estoque = 10,
                            ImagemUrl = "/img/cafe.jpg",
                            Nome = "Cupcake de Café",
                            Preco = 9.80m
                        },
                        new
                        {
                            Id = 14,
                            Categoria = 4,
                            Descricao = "Massa suave e cobertura cremosa de pistache",
                            Destaque = false,
                            Estoque = 10,
                            ImagemUrl = "/img/pistache.jpg",
                            Nome = "Cupcake de Pistache",
                            Preco = 12.00m
                        },
                        new
                        {
                            Id = 15,
                            Categoria = 3,
                            Descricao = "Sabor cítrico com toque de gengibre natural",
                            Destaque = false,
                            Estoque = 10,
                            ImagemUrl = "/img/laranja.jpg",
                            Nome = "Cupcake de Laranja com Gengibre",
                            Preco = 9.00m
                        },
                        new
                        {
                            Id = 16,
                            Categoria = 4,
                            Descricao = "Recheado com doce de leite e cobertura crocante de nozes",
                            Destaque = false,
                            Estoque = 10,
                            ImagemUrl = "/img/nozes.jpg",
                            Nome = "Cupcake de Doce de Leite com Nozes",
                            Preco = 10.50m
                        },
                        new
                        {
                            Id = 17,
                            Categoria = 1,
                            Descricao = "Sabor caseiro com toque de canela",
                            Destaque = false,
                            Estoque = 10,
                            ImagemUrl = "/img/banana.jpg",
                            Nome = "Cupcake de Banana com Canela",
                            Preco = 8.50m
                        },
                        new
                        {
                            Id = 18,
                            Categoria = 1,
                            Descricao = "Cobertura cremosa de chocolate branco e raspas finas",
                            Destaque = true,
                            Estoque = 10,
                            ImagemUrl = "/img/chocolatebranco.jpg",
                            Nome = "Cupcake de Chocolate Branco",
                            Preco = 10.00m
                        },
                        new
                        {
                            Id = 19,
                            Categoria = 1,
                            Descricao = "Sabor refrescante com pedaços de chocolate meio amargo",
                            Destaque = false,
                            Estoque = 10,
                            ImagemUrl = "/img/menta.jpg",
                            Nome = "Cupcake de Menta com Chocolate",
                            Preco = 9.70m
                        },
                        new
                        {
                            Id = 20,
                            Categoria = 4,
                            Descricao = "Equilíbrio perfeito entre doce e cítrico",
                            Destaque = false,
                            Estoque = 10,
                            ImagemUrl = "/img/framboesa.jpg",
                            Nome = "Cupcake de Framboesa com Limão Siciliano",
                            Preco = 11.20m
                        },
                        new
                        {
                            Id = 21,
                            Categoria = 1,
                            Descricao = "70% cacau com cobertura de ganache",
                            Destaque = false,
                            Estoque = 10,
                            ImagemUrl = "/img/chocolateamargo.jpg",
                            Nome = "Cupcake de Chocolate Amargo",
                            Preco = 10.00m
                        },
                        new
                        {
                            Id = 22,
                            Categoria = 1,
                            Descricao = "Tradicional massa de baunilha com cobertura leve",
                            Destaque = true,
                            Estoque = 10,
                            ImagemUrl = "/img/baunilha.jpg",
                            Nome = "Cupcake de Baunilha Clássico",
                            Preco = 7.90m
                        },
                        new
                        {
                            Id = 23,
                            Categoria = 1,
                            Descricao = "Cobertura de paçoca e farofa crocante",
                            Destaque = false,
                            Estoque = 10,
                            ImagemUrl = "/img/pacoca.jpg",
                            Nome = "Cupcake de Paçoca",
                            Preco = 9.30m
                        },
                        new
                        {
                            Id = 24,
                            Categoria = 2,
                            Descricao = "Cobertura cítrica e toque suave de coco",
                            Destaque = false,
                            Estoque = 10,
                            ImagemUrl = "/img/limaococo.jpg",
                            Nome = "Cupcake de Limão Siciliano com Coco",
                            Preco = 9.80m
                        },
                        new
                        {
                            Id = 25,
                            Categoria = 4,
                            Descricao = "Recheado com brigadeiro e cobertura granulada",
                            Destaque = true,
                            Estoque = 10,
                            ImagemUrl = "/img/brigadeiro.jpg",
                            Nome = "Cupcake de Brigadeiro Gourmet",
                            Preco = 10.50m
                        },
                        new
                        {
                            Id = 26,
                            Categoria = 4,
                            Descricao = "Inspirado em cheesecake com calda de morango",
                            Destaque = false,
                            Estoque = 10,
                            ImagemUrl = "/img/cheesecake.jpg",
                            Nome = "Cupcake de Cheesecake com Morango",
                            Preco = 12.00m
                        },
                        new
                        {
                            Id = 27,
                            Categoria = 3,
                            Descricao = "Sem leite e ovos, com manga e maracujá",
                            Destaque = false,
                            Estoque = 10,
                            ImagemUrl = "/img/tropicais.jpg",
                            Nome = "Cupcake Vegano de Frutas Tropicais",
                            Preco = 10.50m
                        },
                        new
                        {
                            Id = 28,
                            Categoria = 7,
                            Descricao = "Combinação ousada e levemente picante",
                            Destaque = false,
                            Estoque = 10,
                            ImagemUrl = "/img/chocolatepimenta.jpg",
                            Nome = "Cupcake de Chocolate com Pimenta",
                            Preco = 9.90m
                        },
                        new
                        {
                            Id = 29,
                            Categoria = 4,
                            Descricao = "Recheado com caramelo salgado e cobertura amanteigada",
                            Destaque = true,
                            Estoque = 10,
                            ImagemUrl = "/img/caramelo.jpg",
                            Nome = "Cupcake de Caramelo Salgado",
                            Preco = 11.30m
                        },
                        new
                        {
                            Id = 30,
                            Categoria = 3,
                            Descricao = "Sabor tropical e refrescante",
                            Destaque = false,
                            Estoque = 10,
                            ImagemUrl = "/img/abacaxi.jpg",
                            Nome = "Cupcake de Abacaxi com Hortelã",
                            Preco = 9.60m
                        });
                });

            modelBuilder.Entity("CupcakeStore.Models.CupomDesconto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CupcakeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EhValorFixo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsoAtual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsoMaximo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CupcakeId");

                    b.ToTable("Cupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Codigo = "PROMO10",
                            CriadoEm = new DateTime(2025, 11, 9, 15, 42, 37, 144, DateTimeKind.Local).AddTicks(4101),
                            EhValorFixo = false,
                            ExpiraEm = new DateTime(2025, 12, 9, 15, 42, 37, 144, DateTimeKind.Local).AddTicks(4115),
                            UsoAtual = 0,
                            UsoMaximo = 100,
                            Valor = 10m
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Codigo = "CUPCAKE5",
                            CriadoEm = new DateTime(2025, 11, 9, 15, 42, 37, 144, DateTimeKind.Local).AddTicks(4122),
                            EhValorFixo = true,
                            ExpiraEm = new DateTime(2026, 1, 9, 15, 42, 37, 144, DateTimeKind.Local).AddTicks(4123),
                            UsoAtual = 0,
                            UsoMaximo = 0,
                            Valor = 5m
                        });
                });

            modelBuilder.Entity("CupcakeStore.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("CupcakeStore.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("CupcakeStore.Models.PedidoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CupcakeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CupcakeId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoItens");
                });

            modelBuilder.Entity("CupcakeStore.Models.Avaliacao", b =>
                {
                    b.HasOne("CupcakeStore.Models.Pedido", "Pedido")
                        .WithOne("Avaliacao")
                        .HasForeignKey("CupcakeStore.Models.Avaliacao", "PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("CupcakeStore.Models.CupomDesconto", b =>
                {
                    b.HasOne("CupcakeStore.Models.Cupcake", "Cupcake")
                        .WithMany()
                        .HasForeignKey("CupcakeId");

                    b.Navigation("Cupcake");
                });

            modelBuilder.Entity("CupcakeStore.Models.Endereco", b =>
                {
                    b.HasOne("CupcakeStore.Models.Cliente", "Cliente")
                        .WithMany("Enderecos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CupcakeStore.Models.Pedido", b =>
                {
                    b.HasOne("CupcakeStore.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CupcakeStore.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("CupcakeStore.Models.PedidoItem", b =>
                {
                    b.HasOne("CupcakeStore.Models.Cupcake", "Cupcake")
                        .WithMany()
                        .HasForeignKey("CupcakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CupcakeStore.Models.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cupcake");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("CupcakeStore.Models.Cliente", b =>
                {
                    b.Navigation("Enderecos");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("CupcakeStore.Models.Pedido", b =>
                {
                    b.Navigation("Avaliacao")
                        .IsRequired();

                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
